[project]
name = "Blog"
version = "0.1.0"
description = "Beyond 400 the blog"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2",
    "djangorestframework>=3.16.0",
    "python-decouple>=3.8",
]
